### ISSUE TITLE
no low latency cache available error

### ISSUE THREAD

**Issue by vgezer** [owncloud/shorty#118] opened 2015-02-17 15:08 UTC
After using the generated link.

Using latest git-master branch with tracking app enabled.

Using the generated URL on browser gives a blank page and an error message. The full error message on log is:

~~~
{"reqId":"LqwPkzHtDTWDFaGj83qa","remoteAddr":"127.0.0.1","app":"memcache","message":"no low latency cache available","level":0,"time":"2015-02-17T15:04:54+00:00","method":"GET","url":"\/oc_git\/public.php?service=shorty_relay&id=bwbEgTO9Bl"}
~~~

Ubuntu 15.04 Dev Apache 2.4.10 server

**Comment by arkascha** [comment] 2015-02-17 20:40
First: thanks for the feedback! 
Next: sorry to say so, but from your description I have no idea what the issue is here. On first glance this does not look like  Shorty bug to me, but some general setup problem. Shorty itself does not use "memcache" at all, this is something from the OC core, so I assume that we are looking at some sort of routing problem or the like. 

Maybe you could add some more information like your Shorty setup (admin settings page) and your users Shorty preferences (cog wheel upper right)? Then also the details of the Shorty that fails might be of interest...

**Comment by fredl99** [comment] 2015-02-18 00:16
> Ubuntu 15.05 Dev Apache 2.4.10 server
There will be no version 15.05 of Ubuntu. 
15.04. would be the upcoming release, which is still in alpha state. (note "Dev"...) It
So the issue could be caused by the OS or any involved component itself. And maybe disappear with the next upgrade.

**Comment by wakeup** [comment] 2015-02-18 01:00
@fredl99 

> There will be no version 15.05 of Ubuntu. 

Ah, thanks for noticing it. I fixed that.

@arkascha I will update the ticket tomorrow.

**Comment by fredl99** [comment] 2015-02-18 09:20
@wakeup 
I was trying to say, I'd suggest to cross-check with a stable release of the/any OS. Packages in Alpha releases can have rough edges that sometimes cause friction.

**Comment by wakeup** [comment] 2015-02-18 15:31
@fredl99 I see, but unfortunately I do not have a second PC to test it.

@arkascha If you want I can also give you a user account so that you can check it? I think I can find your email.

**Comment by wakeup** [comment] 2015-02-18 15:33
Shorty settings:

![image](https://cloud.githubusercontent.com/assets/231068/6250076/c6c30484-b78b-11e4-82a1-d20c12cdd2dc.png)


Admin settings:

![image](https://cloud.githubusercontent.com/assets/231068/6250086/d9cb5c98-b78b-11e4-9fca-08477eba6ad7.png)

**Comment by fredl99** [comment] 2015-02-18 16:09
@wakeup Have you seen [this](https://github.com/owncloud/core/issues/14334)?
And what's the error message from the browser?
You could install a stable OS in a virtual machine. Hunting bugs is hard when you can't rule out anything.

**Comment by wakeup** [comment] 2015-02-22 12:23
Yes @fredl99 I checked it, but merging this did not solve the issue.

Here is what I have tried so far:

Install fresh ownCloud 7 and download Shorty from appstore -> works
Install fresh ownCloud 8 and download Shorty from appstore -> does not work
Install fresh ownCloud 8 and use git-master branch of Shorty -> works
ownCloud 8 fresh git-master and use git-master branch of Shorty -> does not work

Seems like a regression in core. I will open another issue in core if you agree.

**Comment by arkascha** [comment] 2015-02-22 12:44
Certainly, go ahead. 
I have to admit that I did not look deeper into this, since I found no hint that this has anything to do with the Shorty app. I do not know what the problem is. But as written before the Shorty app does not use such features at all in any direct manner. 

Don't get that wrong please, I do not doubt there is a problem. 
But I think it makes more sense to concentrate on the bugs inside the apps code for me. 

One question: could you please link to issue you open in here so that it can be tracked? Thanks!

**Comment by wakeup** [comment] 2015-02-22 14:46
Before submitting the issue, I have seen my apache2 accesslogs and the entry Shorty created is not found (404), appearently... Maybe I can investigate further if you can guide me:

~~~
127.0.0.1 - - [22/Feb/2015:15:44:13 +0100] "GET /oc-git/public.php?service=shorty_relay&id=jh39X9X7U HTTP/1.1" 404 612 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/40.0.2214.111 Chrome/40.0.2214.111 Safari/537.36"
~~~

**Comment by arkascha** [comment] 2015-02-22 15:17
That looks like relaying request to a shorty, so an attempt to open the target a Shorty points to. 
If such a request results in a 404 then there are two possible causes: 
1. there simply is no Shorty with ID jh39X9X7U in your database, maybe it was removed? Shorty does indeed reply with a 404 error in that case. 
2. there is some issue with your relaying configuration: is the url of your test installation really http://some-system.org/oc-git ? I sometimes realize that in tests I am using an outdated configuration of a static backend which leads to an installation not available any more :-)

This is all a little guessing. I might be able to tell you more if you post your setup.

**Comment by wakeup** [comment] 2015-02-22 17:54
This is the database output:

~~~
sqlite> SELECT `rowid`,* FROM `oc_shorty`  ORDER BY `rowid` ASC

3|jh39X9X7U|public|Google|http://www.google.de/favicon.ico|http://is.gd/eCrJWy|admin||2015-02-22|0|0|http://google.com|
~~~

so it means 1st assumption works.

My ownCloud config is:

~~~
<?php
DEFINE('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'xx',
  'passwordsalt' => 'xx',
  'secret' => 'xxxx',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/volkan/oc-git/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/home/volkan/oc-git/appsstore',
      'url' => '/appsstore',
      'writable' => true,
    ),
    2 => 
    array (
      'path' => '/home/volkan/oc-git/apps2',
      'url' => '/apps2',
      'writable' => false,
    ),
  ),
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'xxxx',
  ),
  'datadirectory' => '/home/volkan/oc-git/data',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.9',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);
~~~

Shorty config in oc_appconfig:

~~~
sqlite> SELECT `rowid`,* FROM `oc_appconfig` WHERE appid='shorty'  ORDER BY `rowid` ASC LIMIT 0, 5000;
89|shorty|installed_version|0.5.1
93|shorty|types|type
94|shorty|enabled|yes
108|shorty|backend-selection|none,isgd,google,tinyurl
109|shorty|id-alphabet|vFLNul84Irt7EVOTjHiKnWUM2DA6Ywzqw91GPspaCkxedbXmRJ350ochQZfgBS
~~~

**Comment by arkascha** [comment] 2015-03-13 20:39
@vgezer Any update here on your site?

**Comment by vgezer** [comment] 2015-04-06 17:17
@arkascha Sorry for late answer. I am unable to activate the app. I had to format my pc and now cannot see shorty in app list.

**Comment by arkascha** [comment] 2015-04-06 17:50
The access to apps offered on apps.owncloud.com is apparently broken. Has been for quite a while. Apparently the core team does not see this as an urgent issue. Nothing more I can say here. I do not understand that politic myself. 

So you have to install the app manually for the time being. Download it from apps.owncloud.com und unpack the zip archive into the "apps" folder of your owncloud installation. The folder has to be called "shorty". Afterwards the app should be offered for activation in owncloud.

**Comment by arkascha** [comment] 2016-01-22 08:11
Closing this issue as "outdated and not getting updated".

**Closed by arkascha** 2016-01-22 08:11 UTC
Labels: bug
