### ISSUE TITLE
SQL error while installing on 8.0.0

### ISSUE THREAD

**Issue by chadrien** [owncloud/shorty#121] opened 2015-02-20 19:47 UTC
> An exception occurred while executing 'CREATE TABLE `oc_shorty` (`id` VARCHAR(12) NOT NULL, `status` VARCHAR(10) DEFAULT 'shared' NOT NULL, `title` VARCHAR(1024) DEFAULT '' NOT NULL, `favicon` VARCHAR(1024) DEFAULT NULL, `source` VARCHAR(500) NOT NULL, `target` VARCHAR(4096) NOT NULL, `user` VARCHAR(64) NOT NULL, `until` DATE DEFAULT NULL, `created` DATE DEFAULT NULL, `accessed` BIGINT UNSIGNED DEFAULT 0, `clicks` BIGINT UNSIGNED DEFAULT 0 NOT NULL, `notes` VARCHAR(4096) DEFAULT '' NOT NULL, UNIQUE INDEX index_shorty_id (`id`), INDEX index_shorty_user (`user`), INDEX index_shorty_source (`source`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Owncloud version: 8.0.0
Shorty version: 0.4.4
PHP: 5.6
MySQL: 5.6.23

I don't think its really related to the owncloud version, but who knows :smiley:

**Comment by arkascha** [comment] 2015-02-20 21:42
Thanks for the feedback, always welcome! 
Hm, this is strange... It is a well known trap every developer runs into sooner or later when setting up databases: the limitation of the total length of the indexes when creating tables is somewhat surprising, though pretty logical once you start thinking about it. So I took care of exactly this issue many month ago, so this puzzles me. 

"""Specified key was too long; max key length is 767 bytes"""
Now if we look at the indexes defined here we see three: 
- UNIQUE INDEX index_shorty_id (id) (length 12)
- INDEX index_shorty_user (user) (length 64)
- INDEX index_shorty_source (source) (length 500)
This makes a total length of 576 plus some fixed additive. Which is, as we probably all agree, lower than  767. Spontaneously I would point into the direction of utf encoding as a reason why that limit is broken. But then again I have no problems executing exactly that sql statement in a few of my mysql servers. So I fail to reproduce that issue. 

Now I do see that you are trying to install an outdated version of Shorty. Please note that the version published on the app store is not approved. So not offered for install. That is because it is not usable. Especially it is not working under OC8. I am surprised you got that far at all...
However let's not make things that easy for ourselves... Even at that version the issue you report her should not occur, since the cause has been taken into account before that version was released. 

That is why currently I do not have a cue what is going on here. 
Could I ask you a favor: please have a try installing the current master of this app into your system. Since you report an issue here you obviously have a github account, so I assume you are familiar with doing that. Do you run into the same problem? Or is the issue resolved that way? 
(the app won't be usable even then, the current state is buggy, I am working on fixing the last remaining issues.)

**Comment by chadrien** [comment] 2015-02-20 21:55
Oh sure, I took the version from the store as I though it would be up to date.

If it's not, and the master branch is stable enough, I'll make to use this instead :smile:

**Comment by chadrien** [comment] 2015-02-20 22:01
Same issue with the master version :crying_cat_face:

**Comment by arkascha** [comment] 2015-02-23 10:48
Sure, as already written in my last comment: 
the changes fixing the known issue with index length were introduced before Shorty-0.4.4. Therefore there are no changes to that aspect in current master. 

I know this is frustrating, sorry again. But as written before I have no clue what is going on...
One reason might be that you have a somewhat special, non default configuration inside your mysql server. As said: I am unable to reproduce that issue on any of my servers. If you want to share your configuration to tackle this down you are welcome. If you have details you don't want to publish here then you will find an email address to reach me in the head of every single file of the apps code.

**Comment by fredl99** [comment] 2015-02-23 13:28
I'm no expert with SQL, but this could have to do with UTF8 in (a lose) conjunction with InnoDB: [Look here](http://stackoverflow.com/a/16820166)

**Comment by arkascha** [comment] 2015-03-14 19:24
@fredl99 I do not see a connection here... The index in the source column (which might be the culprit here) is not unique. If that limitation _really would strike here_, then it should be generally impossible to activate the app using utf encoding. I myself cannot reproduce this nor have I heard of any other report since the last changes to the index setup. 

@chadrien: I tried again on a mysql server and had no issues installing and activating the Shorty app...

**Comment by arkascha** [comment] 2016-01-22 08:10
Closing this issue as "outdated and not getting updated".

**Closed by arkascha** 2016-01-22 08:10 UTC
